# Generated by Django 4.0.6 on 2022-08-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='img',
            field=models.ImageField(blank=True, help_text='Seleccione una imagen para mostrar', null=True, upload_to='images/noticias'),
        ),
    ]
